exports.homePage = function(d){
    return `
    <!DOCTYPE html>
    <html>
    
    <head>
        <meta charset="UTF-8" />
        <link rel="icon" href="favicon.png" />
        <link rel="stylesheet" href="w3.css" />
        <title>Home Page - TPC4</title>
    </head>
    
    <body>
        <div class="w3-card-4">
    
            <header class="w3-container w3-teal">
                <h1>TPC4</h1>
    
            </header>
    
            <div class="w3-container">
                <ul class="w3-ul">
                    <li><a href="/compositores">Compositores</a></li>
                    <li><a href="/periodos">Periodos</a></li>
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
            </footer>
        </div>
    </body>
    
    </html>
    `
}

exports.composersListPage = function(clist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Gestão de compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    <a href="/">Home Page</a>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>Periodo</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td>
                        <a href="/compositores/${clist[i].id}">
                            ${clist[i].nome}
                        </a>
                    </td>
                    <td><a href="periodos/${clist[i].periodo.id}">${clist[i].periodo.nome}</a></td>
                    <td>
                        [<a href="/compositores/edit/${clist[i].id}">Edit</a>] [<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.composerFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Composer Form</h2>
                    <a href="javascript:history.back()">Voltar</a>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="textarea" name="bio"/>
                        <label>Date de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Date da Morte</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="Submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
                </footer>
            
            </div>
    `
}

exports.composerFormEditPage = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Composer Form</h2>
                    <a href="javascript:history.back()">Voltar</a>
                </header>
            
                <form class="w3-container" method="POST">
                <fieldset>
                    <legend>Metadata</legend>
                    <label>id</label>
                    <input class="w3-input w3-round" type="text" name="id" readonly value='${c.id}'/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value='${c.nome}'/>
                    <label>Bio</label>
                    <input class="w3-input w3-round" type="textarea" name="bio" value='${c.bio}'/>
                    <labal>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="date" name="dataNasc" value='${c.dataNasc}'/>
                    <label>Date da Morte</label>
                    <input class="w3-input w3-round" type="date" name="dataObito" value='${c.dataObito}'/>
                    <label>Periodo</label>
                    <input class="w3-input w3-round" type="text" name="periodo" value='${c.periodo.nome}'/>
                </fieldset>
                    `

    pagHTML += `
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="Submit">Edit</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.compositoresPorPeriodoListPage = function(clist, pInfo,d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Gestão de compositores por período</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de compositores do período
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    <a href="/">Home Page</a>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>Periodo</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td>
                        <a href="/compositores/${clist[i].id}">
                            ${clist[i].nome}
                        </a>
                    </td>
                    <td>${pInfo.nome}</td>
                    <td>
                        [<a href="/compositores/edit/${clist[i].id}">Edit</a>] [<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// ---------------Composer's Page--------------------------------

exports.composerPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.nome}</h1>
                <a href="javascript:history.back()">Voltar</a>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:100%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Número: </b> ${compositor.id}</li>
                    <li><b>Biografia: </b> ${compositor.bio}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Periodo: </b> <a href='/periodos/${compositor.periodo.id}'>${compositor.periodo.nome}</a></li>
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por A95076::EngWeb2024 em ${d}</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.periodsListPage = function(plist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Gestão de Períodos</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                <h1>Lista de Períodos
                <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                </h1>
                <a href="/">Home Page</a>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < plist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${plist[i].id}</td>
                    <td>
                        <a href="/periodos/${plist[i].id}">
                            ${plist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${plist[i].id}">Edit</a>] [<a href="/periodos/delete/${plist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Period Form</h2>
                    <a href="javascript:history.back()">Voltar</a>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
                </footer>
            
            </div>
    `
}

exports.periodFormEditPage = function(p, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Period Form</h2>
                    <a href="javascript:history.back()">Voltar</a>
                </header>
            
                <form class="w3-container" method="POST">
                <fieldset>
                    <legend>Metadata</legend>
                    <label>id</label>
                    <input class="w3-input w3-round" type="text" name="id" readonly value='${p.id}'/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value='${p.nome}'/>
                </fieldset>
                <button class="w3-btn w3-teal w3-mb-2" type="Submit">Edit</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by A95076::EngWeb2024 in ${d}</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}